### PR TITLE
Add ability to have poll name differ from resource name

### PR DESCRIPTION
**Pull request by tojofo**
What it says on the tin

### CODE REVIEW

**Comment by tojofo** [comment]
Apologies this PR was meant to go against our own master branch.  Closing.

**Comment by mfpiccolo** [comment]
I haven't been keeping this up to date lately but I would be happy to do so if you are interested in updating and opening a PR here when you are done.

**Comment by tojofo** [comment]
Hey, thanks for the quick response!

My main concerns are that my changes are not backwards compatible and that I have change some variables from C style underscores to JS camelCase.

I'm happy to rollback the variable name changes but I worry about the backwards compatibility side of things, you can view my changes here https://github.com/Biteable/ember-cli-poll/pull/1

If you have time, take a look, pass on your thoughts and I'll see what I can do.

**Comment by mfpiccolo** [comment]
Well since we are only at 0.0.9 it shouldn't be a problem if it is an improvement.  I will just bump to 0.1.0.  That is what semver is for (although I am probably not following it correctly) :grin: 

I will take a look.  If it is an improvement then I would like to keep this repo moving forward instead of having multiple forks.

**Comment by mfpiccolo** [comment]
@tojofo This looks fine to me.  I am not a fan of camel casing for variables so if you can live with the underscores then roll those back and I will merge and release 0.1.0.  

The changes are minor so I don't think it will be that big of an issue.  If it is then devs should lock their version.

Perhaps we could add a changelog that follows this standard: https://github.com/sgrif/diesel/blob/master/CHANGELOG.md

**Comment by tojofo** [comment]
Ok cool, I am about to wrap up for the day so I'll revert the camel casing and submit a PR tomorrow.  Thanks for being so understanding.  I'll take care of the change log too.

**Pull request closed without merging**
